# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20160209_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='correo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(default=True, max_length=255),
        ),
    ]
