# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20160213_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(max_length=255),
        ),
    ]
